### PR TITLE
155 merge vex reference check doesnt take nested components into account

### LINKED ISSUE #155: `merge-vex` reference check doesn't take nested components into account
The following piece of code doesn't take nested components into account:

https://github.com/Festo-se/cyclonedx-editor-validator/blob/8bdf8fd2195b68c18a9f76d74146a8f8d14550a3/cdxev/merge_vex.py#L32-L49

That means, if your vulnerabilities reference a nested component, the merge will fail.

### PR DESCRIPTION
**Pull request by CBeck-96**
closes #155
depends on #154

### CODE REVIEW

**Comment by italvi** [comment]
@CBeck-96 do you really want to add this now without tests? As a rework of vex is planned, I am uncertain whether this half PR is justified.

**Comment by CBeck-96** [comment]
> @CBeck-96 do you really want to add this now without tests? As a rework of vex is planned, I am uncertain whether this half PR is justified.

It closed an issue with < 5min works... But it will probably be not relevant, depending on the new vex functions

**Comment by italvi** [comment]
> > @CBeck-96 do you really want to add this now without tests? As a rework of vex is planned, I am uncertain whether this half PR is justified.
> 
> It closed an issue with < 5min works... But it will probably be not relevant, depending on the new vex functions

Still, it misses test. Please either add tests or close this PR for the time-being, waiting for the rework of `merge-vex`

**Comment by CBeck-96** [comment]
Since merge vex is deprecated, PR will be closed until the feature is reworked.

**Pull request closed without merging**
